# Generated by Django 5.0.2 on 2024-03-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_rename_employee_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('employee', models.CharField(max_length=20)),
                ('ID_no', models.CharField(max_length=20)),
                ('phone_no', models.CharField(max_length=20)),
            ],
        ),
    ]
